In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"D:\downloads\Unclean Dataset.csv", encoding="ISO-8859-1")
df= df.round()
print(df)

                                           Student_ID   First_Name   \
0    101        | John       | Smith     | 22  | M ...          NaN
1    102        | Emily      | Johnson   | 24  | F ...          NaN
2    103        | Michael    | Williams  | 21  | M ...          NaN
3    104        | Sarah      | Brown     | 23  | F ...          NaN
4    105        | David      | Davis     | 20  | M ...          NaN
..                                                 ...          ...
131  232        | Amina      | Adekunle    | 21  | ...          NaN
132  234       | Ibrahim    | Okafor      | 22  | M...          NaN
133  235        | Zainab     | Abiodun     | 23  | ...          NaN
134  236        | Nasiru     | Adebayo     | 24  | ...          NaN
135  237       | Aisha      | Okonkwo     | 25  | F...          NaN

     Last_Name   Age   Gender   Course   Enrollment_Date   Total_Payments
0           NaN   NaN      NaN      NaN               NaN             NaN
1           NaN   NaN      NaN      NaN               NaN             NaN
2           NaN   NaN      NaN      NaN               NaN             NaN
3           NaN   NaN      NaN      NaN               NaN             NaN
4           NaN   NaN      NaN      NaN               NaN             NaN
..          ...   ...      ...      ...               ...             ...
131         NaN   NaN      NaN      NaN               NaN             NaN
132         NaN   NaN      NaN      NaN               NaN             NaN
133         NaN   NaN      NaN      NaN               NaN             NaN
134         NaN   NaN      NaN      NaN               NaN             NaN
135         NaN   NaN      NaN      NaN               NaN             NaN

[136 rows x 8 columns]

In [4]:
df.head()

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
0,101 | John | Smith | 22 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,102 | Emily | Johnson | 24 | F ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,103 | Michael | Williams | 21 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,104 | Sarah | Brown | 23 | F ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105 | David | Davis | 20 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns.to_list()

['Student_ID ',
 ' First_Name ',
 ' Last_Name ',
 ' Age ',
 ' Gender ',
 ' Course ',
 ' Enrollment_Date ',
 ' Total_Payments']

In [6]:
print(df.loc[116, 'Student_ID '])

217       | Chukwudi   |     | 22  | M      | Data Science     | 2022-05-15      | $1200

In [7]:
df.tail(45)

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
91,Zainab Adeyemi,Zainab Adeyemi,NaN,19,f,Cyber Security,01-Jul-22,"? 370,012"
92,Obinna Onwuka,Obinna Onwuka,NaN,25,f,Data Analysis,09-Jul-23,"? 407,014"
93,Amina Osagie,Amina Osagie,NaN,40,M,Data Analysis,01-Aug-05,"? 447,715"
94,Chinonso Uche,Chinonso Uche,NaN,23,M,Data Analysis,28-Jul-23,"? 492,487"
95,Femi Abdullahi,Femi Abdullahi,NaN,22,M,Data Analysis,01-Jul-23,"? 541,735"
96,Halima Bakare,Halima Bakare,NaN,23,M,Data Analysis,17-Jul-22,"? 595,909"
97,Chibuzo Mohammed,Chibuzo Mohammed,NaN,21,M,Data Analysis,01-Sep-20,"? 655,500"
98,Oluchi Iwuoha,Oluchi Iwuoha,NaN,22,F,Machine Learning,31-Jan-21,"? 721,050"
99,Emeka Anikulapo,Emeka Anikulapo,NaN,19,M,Data Analysis,19-Jul-24,"? 793,155"
100,Hadiza Ogundipe,Hadiza Ogundipe,NaN,18,M,Data Analysis,06-Aug-22,"? 872,470"
101,Nneka Nwachukwu,Nneka Nwachukwu,NaN,4,M,Web Develpment,01-Aug-23,"? 959,717"
102,Adeola Okoro,Adeola Okoro,NaN,NaN,M,Web Develpment,12-Jul-23,"? 1,055,689"
103,Idris Ibrahim,Idris Ibrahim,NaN,23,M,Web Develpment,31-Aug-24,"? 1,161,258"
104,Chinyere Adeyemi,Chinyere Adeyemi,NaN,23,M,NaN,07-Oct-22,"? 1,277,383"
105,Umar Abdullahi,Umar Abdullahi,NaN,22,M,Web Develpment,01-Jul-24,"? 1,405,122"
106,Nkem Adebayo,Nkem Adebayo,NaN,20,M,Web Develpment,21-Jul-24,"? 1,545,634"
107,Ayodele Osagie,Ayodele Osagie,NaN,22,F,Machine Learning,30-Jan-21,"? 1,700,197"
108,Chiwendu Ekpo,Chiwendu Ekpo,NaN,21,M,Machine Learning,30-Jan-20,"? 1,870,217"
109,Fatima Azikiwe,Fatima Azikiwe,NaN,22,F,Data Analysis,01-Jul-21,"? 2,057,239"
110,Chukwudi Ekeinde,Chukwudi Ekeinde,NaN,19,M,Cyber Security,28-Aug-22,"? 2,262,963"
111,Kemi Uche,Kemi Uche,NaN,18,M,Cyber Security,06-Jul-22,"? 2,489,259"
112,Jide Bakare,Jide Bakare,NaN,18,M,Cyber Security,02-Sep-23,"? 2,738,185"
113,Adaobi Iwuoha,Adaobi Iwuoha,NaN,19,M,Cyber Security,06-Aug-22,"? 3,012,003"
114,Suleiman Mohammed,Suleiman Mohammed,NaN,23,M,Cyber Security,25-Sep-20,"? 3,313,204"
115,Ifeoluwa Anikulapo,Ifeoluwa Anikulapo,NaN,23,M,Cyber Security,31-Aug-23,"? 3,644,524"
116,217 | Chukwudi | | 22 | M | ...,Ogechi Ogundipe,NaN,NaN,NaN,NaN,NaN,NaN
117,218 | Ngozi | Eze | 24 | F ...,Abubakar Okonkwo,NaN,NaN,NaN,NaN,NaN,NaN
118,219 | Ifeoluwa | Adewale | 21 | M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,220 | Ada | Adeleke | 23 | F ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,221 | Kehinde | Bakare | 20 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,222 | Amara | Okonkwo | 25 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,223 | Uche | Adebayo | 19 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,224 | Nneka | Nwachukwu | 22 | F ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,225 | Emeka | Okafor | 24 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,226 | Chinyere | Nwosu | 26 | F...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,227 | Obinna | Onyekachi | 20 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,228 | Chinwe | Okoye | 23 | F...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,229 | Ugochukwu | Okafor | 21 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,230 | Ijeoma | Uzoma | 22 | F ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,231 | Obi | Okonkwo | 24 | M ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,232 | Amina | Adekunle | 21 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,234 | Ibrahim | Okafor | 22 | M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,235 | Zainab | Abiodun | 23 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,236 | Nasiru | Adebayo | 24 | ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,237 | Aisha | Okonkwo | 25 | F...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student_ID         132 non-null    object
 1    First_Name        99 non-null     object
 2    Last_Name         18 non-null     object
 3    Age               53 non-null     object
 4    Gender            59 non-null     object
 5    Course            54 non-null     object
 6    Enrollment_Date   60 non-null     object
 7    Total_Payments    58 non-null     object
dtypes: object(8)
memory usage: 8.6+ KB

In [9]:
df
df[df[' Age '] > "21"]

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
20,Ayodele,Ayodele,NaN,F,18,Machine Learning,08-09-23,"?37,440.00"
21,NaN,NaN,NaN,M,25,NaN,09-09-22,"?37,488.00"
22,NaN,NaN,NaN,F,25,NaN,10-09-21,"?37,497.60"
35,Joseph,Joseph,Williams,22,F 24,Machine Learning,08-01-23,"£20,000"
36,Kylian,Kylian,Eden,78*,M,Machine Learning,08-01-24,"£20,000"
37,Esther,Esther,Naomi,21*,F,Machine Learning,08-01-22,"£20,000"
38,Lay,Lay,Martin,22,M,Web Developmet,08-01-24,"£20,000"
39,Rock,Rock,Shy,23,M,Data Analytics,02-05-99,NaN
70,Adeniran,Adeniran,Omoshola,22,F,Data Analysis,01-Jul-21,50000
71,Iwueze,Iwueze,Olaoluwa,23,M,Data Analysis,10-Jul-20,"? 55,000"
72,Faramotu Ismail,Faramotu Ismail,NaN,23,M,Data Analysis,16-Jul-20,"? 60,500"
73,Ifarele,Ifarele,Adeola,23,M,Data Analysis,30-Aug-22,"? 66,550"
74,Folorunsho,Folorunsho,Dada,22,M,Web Development,01-Jul-22,"? 73,205"
75,Ikechukwu,Ikechukwu,Victor,22,M,Web Development,01-Jul-24,"? 80,526"
76,Ahmed,Ahmed,Mohammed,23,F,Web Development,19-Jul-21,"? 88,578"
77,Binta,Binta,Sanni,22,F,Web Development,01-Jul-21,"? 97,436"
78,Chukwu,Chukwu,Ike,22,M,Web Development,01-Jul-22,"? 107,179"
79,Ola Enioluwa,Ola Enioluwa,NaN,22,F,Machine Learning,01-Jan-21,"? 117,897"
80,Okafor,Okafor,Chike,23,M,Data Analysis,11-Jul-20,"? 129,687"
81,Chika Nwosu,Chika Nwosu,NaN,23,F,Data Analysis,09-Aug-21,"? 142,656"
82,Eze Chinedu,Eze Chinedu,NaN,22,M,Data Analysis,01-Jul-23,"? 156,921"
83,Adaobi Ekeinde,Adaobi Ekeinde,NaN,23,M,Data Analysis,09-Jul-23,"? 172,614"
84,Yusuf Ibrahim,Yusuf Ibrahim,NaN,22,M,Cyber Security,01-Aug-05,"? 189,875"
85,Amaka Azikiwe,Amaka Azikiwe,NaN,23,M,Cyber Security,28-Jul-23,"? 208,862"
86,Onyeka Okonkwo,Onyeka Okonkwo,NaN,23,f,Cyber Security,16-Jul-16,"? 229,749"
87,Chioma Adebayo,Chioma Adebayo,NaN,22,f,Cyber Security,01-Jul-22,"? 252,724"
88,Ifeanyi Ekpo,Ifeanyi Ekpo,NaN,22,f,Cyber Security,01-Jul-22,"? 277,996"
92,Obinna Onwuka,Obinna Onwuka,NaN,25,f,Data Analysis,09-Jul-23,"? 407,014"
93,Amina Osagie,Amina Osagie,NaN,40,M,Data Analysis,01-Aug-05,"? 447,715"
94,Chinonso Uche,Chinonso Uche,NaN,23,M,Data Analysis,28-Jul-23,"? 492,487"
95,Femi Abdullahi,Femi Abdullahi,NaN,22,M,Data Analysis,01-Jul-23,"? 541,735"
96,Halima Bakare,Halima Bakare,NaN,23,M,Data Analysis,17-Jul-22,"? 595,909"
98,Oluchi Iwuoha,Oluchi Iwuoha,NaN,22,F,Machine Learning,31-Jan-21,"? 721,050"
101,Nneka Nwachukwu,Nneka Nwachukwu,NaN,4,M,Web Develpment,01-Aug-23,"? 959,717"
103,Idris Ibrahim,Idris Ibrahim,NaN,23,M,Web Develpment,31-Aug-24,"? 1,161,258"
104,Chinyere Adeyemi,Chinyere Adeyemi,NaN,23,M,NaN,07-Oct-22,"? 1,277,383"
105,Umar Abdullahi,Umar Abdullahi,NaN,22,M,Web Develpment,01-Jul-24,"? 1,405,122"
107,Ayodele Osagie,Ayodele Osagie,NaN,22,F,Machine Learning,30-Jan-21,"? 1,700,197"
109,Fatima Azikiwe,Fatima Azikiwe,NaN,22,F,Data Analysis,01-Jul-21,"? 2,057,239"
114,Suleiman Mohammed,Suleiman Mohammed,NaN,23,M,Cyber Security,25-Sep-20,"? 3,313,204"
115,Ifeoluwa Anikulapo,Ifeoluwa Anikulapo,NaN,23,M,Cyber Security,31-Aug-23,"? 3,644,524"

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student_ID         132 non-null    object
 1    First_Name        99 non-null     object
 2    Last_Name         18 non-null     object
 3    Age               53 non-null     object
 4    Gender            59 non-null     object
 5    Course            54 non-null     object
 6    Enrollment_Date   60 non-null     object
 7    Total_Payments    58 non-null     object
dtypes: object(8)
memory usage: 8.6+ KB

In [11]:
df_clean= df.dropna() ## Here I decided to remove that rows because its too messy not have pattern need to chech each row by itself and thats not efficient so decided to remove them as wrong data and keep that has useful info. ##
df_clean

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
35,Joseph,Joseph,Williams,22,F 24,Machine Learning,08-01-23,"£20,000"
36,Kylian,Kylian,Eden,78*,M,Machine Learning,08-01-24,"£20,000"
37,Esther,Esther,Naomi,21*,F,Machine Learning,08-01-22,"£20,000"
38,Lay,Lay,Martin,22,M,Web Developmet,08-01-24,"£20,000"
70,Adeniran,Adeniran,Omoshola,22,F,Data Analysis,01-Jul-21,50000
71,Iwueze,Iwueze,Olaoluwa,23,M,Data Analysis,10-Jul-20,"? 55,000"
73,Ifarele,Ifarele,Adeola,23,M,Data Analysis,30-Aug-22,"? 66,550"
74,Folorunsho,Folorunsho,Dada,22,M,Web Development,01-Jul-22,"? 73,205"
75,Ikechukwu,Ikechukwu,Victor,22,M,Web Development,01-Jul-24,"? 80,526"
76,Ahmed,Ahmed,Mohammed,23,F,Web Development,19-Jul-21,"? 88,578"
77,Binta,Binta,Sanni,22,F,Web Development,01-Jul-21,"? 97,436"
78,Chukwu,Chukwu,Ike,22,M,Web Development,01-Jul-22,"? 107,179"
80,Okafor,Okafor,Chike,23,M,Data Analysis,11-Jul-20,"? 129,687"

In [12]:
print(df_clean.columns.tolist())

['Student_ID ', ' First_Name ', ' Last_Name ', ' Age ', ' Gender ', ' Course ', ' Enrollment_Date ', ' Total_Payments']

In [13]:
df_clean.value_counts()

Student_ID    First_Name    Last_Name    Age    Gender    Course            Enrollment_Date    Total_Payments
 Okafor       Okafor       Chike        23     M         Data Analysis     11-Jul-20           ? 129,687         1
Adeniran     Adeniran      Omoshola     22     F         Data Analysis     01-Jul-21          50000              1
Ahmed        Ahmed         Mohammed     23     F         Web Development   19-Jul-21           ? 88,578          1
Binta        Binta         Sanni        22     F         Web Development   01-Jul-21           ? 97,436          1
Chukwu       Chukwu        Ike          22     M         Web Development   01-Jul-22           ? 107,179         1
Esther       Esther        Naomi        21*    F         Machine Learning  08-01-22           £20,000            1
Folorunsho   Folorunsho    Dada         22     M         Web Development   01-Jul-22           ? 73,205          1
Ifarele      Ifarele       Adeola       23     M         Data Analysis     30-Aug-22           ? 66,550          1
Ikechukwu    Ikechukwu     Victor       22     M         Web Development   01-Jul-24           ? 80,526          1
Iwueze       Iwueze        Olaoluwa     23     M         Data Analysis     10-Jul-20           ? 55,000          1
Joseph       Joseph        Williams     22     F 24      Machine Learning  08-01-23           £20,000            1
Kylian       Kylian        Eden         78*    M         Machine Learning  08-01-24           £20,000            1
Lay          Lay           Martin       22     M         Web Developmet    08-01-24           £20,000            1
Name: count, dtype: int64

In [14]:
df_clean[' Total_Payments']= (df_clean[' Total_Payments'].astype(str).str.replace(r"[^\d]", "", regex=True).astype(int)).apply(lambda x: f"${x:,}")
df_clean

C:\Users\oasm2\AppData\Local\Temp\ipykernel_14424\973614148.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[' Total_Payments']= (df_clean[' Total_Payments'].astype(str).str.replace(r"[^\d]", "", regex=True).astype(int)).apply(lambda x: f"${x:,}")

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
35,Joseph,Joseph,Williams,22,F 24,Machine Learning,08-01-23,"$20,000"
36,Kylian,Kylian,Eden,78*,M,Machine Learning,08-01-24,"$20,000"
37,Esther,Esther,Naomi,21*,F,Machine Learning,08-01-22,"$20,000"
38,Lay,Lay,Martin,22,M,Web Developmet,08-01-24,"$20,000"
70,Adeniran,Adeniran,Omoshola,22,F,Data Analysis,01-Jul-21,"$50,000"
71,Iwueze,Iwueze,Olaoluwa,23,M,Data Analysis,10-Jul-20,"$55,000"
73,Ifarele,Ifarele,Adeola,23,M,Data Analysis,30-Aug-22,"$66,550"
74,Folorunsho,Folorunsho,Dada,22,M,Web Development,01-Jul-22,"$73,205"
75,Ikechukwu,Ikechukwu,Victor,22,M,Web Development,01-Jul-24,"$80,526"
76,Ahmed,Ahmed,Mohammed,23,F,Web Development,19-Jul-21,"$88,578"
77,Binta,Binta,Sanni,22,F,Web Development,01-Jul-21,"$97,436"
78,Chukwu,Chukwu,Ike,22,M,Web Development,01-Jul-22,"$107,179"
80,Okafor,Okafor,Chike,23,M,Data Analysis,11-Jul-20,"$129,687"

In [15]:
df_clean[" Age "]=(df_clean[" Age "].astype(str).str.replace(r'[^\d]', "", regex=True).astype(int))
df_clean

C:\Users\oasm2\AppData\Local\Temp\ipykernel_14424\1290360966.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[" Age "]=(df_clean[" Age "].astype(str).str.replace(r'[^\d]', "", regex=True).astype(int))

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
35,Joseph,Joseph,Williams,22,F 24,Machine Learning,08-01-23,"$20,000"
36,Kylian,Kylian,Eden,78,M,Machine Learning,08-01-24,"$20,000"
37,Esther,Esther,Naomi,21,F,Machine Learning,08-01-22,"$20,000"
38,Lay,Lay,Martin,22,M,Web Developmet,08-01-24,"$20,000"
70,Adeniran,Adeniran,Omoshola,22,F,Data Analysis,01-Jul-21,"$50,000"
71,Iwueze,Iwueze,Olaoluwa,23,M,Data Analysis,10-Jul-20,"$55,000"
73,Ifarele,Ifarele,Adeola,23,M,Data Analysis,30-Aug-22,"$66,550"
74,Folorunsho,Folorunsho,Dada,22,M,Web Development,01-Jul-22,"$73,205"
75,Ikechukwu,Ikechukwu,Victor,22,M,Web Development,01-Jul-24,"$80,526"
76,Ahmed,Ahmed,Mohammed,23,F,Web Development,19-Jul-21,"$88,578"
77,Binta,Binta,Sanni,22,F,Web Development,01-Jul-21,"$97,436"
78,Chukwu,Chukwu,Ike,22,M,Web Development,01-Jul-22,"$107,179"
80,Okafor,Okafor,Chike,23,M,Data Analysis,11-Jul-20,"$129,687"

In [16]:
df_clean[" Gender "]=(df_clean[" Gender "].astype(str).str.replace(r"\d", "", regex=True).astype(str))
df_clean

C:\Users\oasm2\AppData\Local\Temp\ipykernel_14424\2724720338.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[" Gender "]=(df_clean[" Gender "].astype(str).str.replace(r"\d", "", regex=True).astype(str))

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
35,Joseph,Joseph,Williams,22,F,Machine Learning,08-01-23,"$20,000"
36,Kylian,Kylian,Eden,78,M,Machine Learning,08-01-24,"$20,000"
37,Esther,Esther,Naomi,21,F,Machine Learning,08-01-22,"$20,000"
38,Lay,Lay,Martin,22,M,Web Developmet,08-01-24,"$20,000"
70,Adeniran,Adeniran,Omoshola,22,F,Data Analysis,01-Jul-21,"$50,000"
71,Iwueze,Iwueze,Olaoluwa,23,M,Data Analysis,10-Jul-20,"$55,000"
73,Ifarele,Ifarele,Adeola,23,M,Data Analysis,30-Aug-22,"$66,550"
74,Folorunsho,Folorunsho,Dada,22,M,Web Development,01-Jul-22,"$73,205"
75,Ikechukwu,Ikechukwu,Victor,22,M,Web Development,01-Jul-24,"$80,526"
76,Ahmed,Ahmed,Mohammed,23,F,Web Development,19-Jul-21,"$88,578"
77,Binta,Binta,Sanni,22,F,Web Development,01-Jul-21,"$97,436"
78,Chukwu,Chukwu,Ike,22,M,Web Development,01-Jul-22,"$107,179"
80,Okafor,Okafor,Chike,23,M,Data Analysis,11-Jul-20,"$129,687"

In [17]:
df_clean.index =df_clean.reset_index(drop=True).index + 1
df_clean

,Student_ID,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
1,Joseph,Joseph,Williams,22,F,Machine Learning,08-01-23,"$20,000"
2,Kylian,Kylian,Eden,78,M,Machine Learning,08-01-24,"$20,000"
3,Esther,Esther,Naomi,21,F,Machine Learning,08-01-22,"$20,000"
4,Lay,Lay,Martin,22,M,Web Developmet,08-01-24,"$20,000"
5,Adeniran,Adeniran,Omoshola,22,F,Data Analysis,01-Jul-21,"$50,000"
6,Iwueze,Iwueze,Olaoluwa,23,M,Data Analysis,10-Jul-20,"$55,000"
7,Ifarele,Ifarele,Adeola,23,M,Data Analysis,30-Aug-22,"$66,550"
8,Folorunsho,Folorunsho,Dada,22,M,Web Development,01-Jul-22,"$73,205"
9,Ikechukwu,Ikechukwu,Victor,22,M,Web Development,01-Jul-24,"$80,526"
10,Ahmed,Ahmed,Mohammed,23,F,Web Development,19-Jul-21,"$88,578"
11,Binta,Binta,Sanni,22,F,Web Development,01-Jul-21,"$97,436"
12,Chukwu,Chukwu,Ike,22,M,Web Development,01-Jul-22,"$107,179"
13,Okafor,Okafor,Chike,23,M,Data Analysis,11-Jul-20,"$129,687"

In [18]:
df_clean=df_clean.drop('Student_ID ', axis=1)
df_clean

,First_Name,Last_Name,Age,Gender,Course,Enrollment_Date,Total_Payments
1,Joseph,Williams,22,F,Machine Learning,08-01-23,"$20,000"
2,Kylian,Eden,78,M,Machine Learning,08-01-24,"$20,000"
3,Esther,Naomi,21,F,Machine Learning,08-01-22,"$20,000"
4,Lay,Martin,22,M,Web Developmet,08-01-24,"$20,000"
5,Adeniran,Omoshola,22,F,Data Analysis,01-Jul-21,"$50,000"
6,Iwueze,Olaoluwa,23,M,Data Analysis,10-Jul-20,"$55,000"
7,Ifarele,Adeola,23,M,Data Analysis,30-Aug-22,"$66,550"
8,Folorunsho,Dada,22,M,Web Development,01-Jul-22,"$73,205"
9,Ikechukwu,Victor,22,M,Web Development,01-Jul-24,"$80,526"
10,Ahmed,Mohammed,23,F,Web Development,19-Jul-21,"$88,578"
11,Binta,Sanni,22,F,Web Development,01-Jul-21,"$97,436"
12,Chukwu,Ike,22,M,Web Development,01-Jul-22,"$107,179"
13,Okafor,Chike,23,M,Data Analysis,11-Jul-20,"$129,687"